name: Build, Test, and Sign Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: false
        tags: ghcr.io/${{ github.repository_owner }}/mmap_benchmark:latest

    - name: Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/mmap_benchmark:latest
        labels: |
          org.opencontainers.image.title=mmap_benchmark
          org.opencontainers.image.description=Benchmark for mmap
          org.opencontainers.image.vendor=YourName
          org.opencontainers.image.licenses=MIT

    - name: Install Cosign
      uses: sigstore/cosign-installer@v2
      with:
        cosign-release: 'v1.4.0'

    - name: Cosign sign
      run: cosign sign --key ${{ secrets.COSIGN_KEY }} ghcr.io/${{ github.repository_owner }}/mmap_benchmark:latest
